<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Configurations>Release;Debug</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="nuget.config" />
    <Compile Remove="Junk/**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="BepInEx.Core" Version="5.4.21" />
		<PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.1-r.0" />
		<PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.11.19">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="R2API.Core" Version="5.3.0" />
		<PackageReference Include="R2API.Prefab" Version="1.1.1" />
		<PackageReference Include="R2API.RecalculateStats" Version="1.6.5" />
		<PackageReference Include="R2API.Language" Version="1.1.0" />
		<PackageReference Include="R2API.Sound" Version="1.0.3" />
		<PackageReference Include="R2API.Items" Version="1.0.7" />
		<PackageReference Include="R2API.DamageType" Version="1.1.7" />
		<PackageReference Include="R2API.Networking" Version="1.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="RiskOfOptions">
	    <HintPath>Libs\RiskOfOptions.dll</HintPath>
	  </Reference>
	  <Reference Include="SYNClib">
	    <HintPath>Libs\SYNClib.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call PostBuild.bat $(TargetPath)" WorkingDirectory="$(ProjectDir)" />
	</Target>
</Project>
